# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: blog@minimal.com
description: "Este é um blog minimalista criado para aprender como funciona esta ferramenta linda que é o Jekyll."
baseurl: ""
url: "http://127.0.0.1:4000/"
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
permalink: /:title/
